# Attributes

## Checking data

### shape
- used to check rows and clumn of array

In [2]:
import numpy as np

arr_2d = np.array([[1,3,4],
                  [5,4,2]])
print(arr_2d.shape)

(2, 3)


## Output
- 2 means number of rows
- 3 means number of cloumns

### Size
- used to check total number of element

In [3]:
import numpy as np

arr_2d = np.array([[1,2,3],
                  [6,5,4]])
print(arr_2d.size)

6


### ndim(number of dimension)

In [6]:
import numpy as np

arr_1d = np.array([1,2,3])
arr_2d = np.array([[3,2,1],[7,6,5]])
arr_3d = np.array([[[1,2,3],[4,5,6],[9,7,6]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


# Output
- 1 mean 1d array
- 2 mean 2d array
- 3 mean 3d array

### dtype(data type of element)

In [7]:
import numpy as np

arr_1d = np.array([1,2.4,3])
print(arr_1d.dtype)


float64


## Changing data type

In [ ]:
import numpy as np

array = np.array([1.2, 3.4, 4.6])
int_array = array.astype(int) # converting float to int using astype() method
int_array[1] = 9  # Update value
print(int_array)
print(int_array.dtype)

[1 9 4]
int64


In [11]:
import numpy as np

arr= np.array([1,2,3])
print(arr + 5)
print(arr * 2)
print(arr **3)

[6 7 8]
[2 4 6]
[ 1  8 27]


# Aggregation function

- Collect the summary from data
- means data average

| function | What it does |
|------------|------------|
| np.sum(array) | Add all elements |
| np.mean(array) | Calculate the Average |
| np.min(array) | Find the minimum value |
| np.max(array) | Find the maximum value |
| np.std(array) | Calculate the standard deviation |
| np.var(array) | Calculate the variance |
--------------------------------------------------------

In [ ]:
import numpy as np

arr = np.array([1,22,44,62,4,8])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))