# Reshaping
- if we want to reshape in that case we just match dimension
- Reshaping does not create cpoy 
- it create a view

# Syntax
- reshape (row, Column)  pecify new shape

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


# Flattening arrays

### . Ravel ()

In [4]:
import numpy as np
arr_2d= np.array([[1,3,4],[5,4,7]]) 
print(arr_2d.ravel()) # Flatten the array
print(arr_2d.flatten()) 

[1 3 4 5 4 7]
[1 3 4 5 4 7]
