# Indexing


# Syntax
- array [index] --> 1D Array
- array [Row, Column] --> Multidimensional Array  or 2D Array


In [3]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])

print(array[4])
print(array[-2])


50
40


# Slicing
- Extracting subset of data

# Syntax
- array[start : stop : step]
- stop --> excluded (if 3 stop then "3-1")
- Negative  step, -1 reverse

In [ ]:
import numpy as np

arr = np.array([10,20,30 ,40 ,50])

print(arr[:4]) # index 0 to 3
print(arr[1:4]) # index 1 to 3
print(arr[::2]) # every second element
print(arr[::-1]) # reverse the array

[10 20 30 40]
[20 30 40]
[10 30 50]
[50 40 30 20 10]


# Fancy Indexing
- selecting multiple element at once
- maximum used when non sequential values access

In [8]:
import numpy as np

arr = np.array([0,10,20,30,40,50,60])

print(arr[[0,3,5]]) # index 0,3,5

[ 0 30 50]


# Boolean Masking / Filtering Data based on Condition

In [10]:
import numpy as np

arr = np.array([0,10,20,30,40,50,60])

print(arr[arr > 20]) # condition based on indexing

[30 40 50 60]
