# Insert

# Syntax
- np.insert(array, index no., value, axis=None)
- array --> Original Array
- index --> position where new value insert
- value --> Actual data that insert
- Axis --> if it None then it addded to a flatten array
- In 2D array working,
- Axis =  Zero(0) --> means data insert Row wise (vertical Stacking)
- Axis = 1 --> means data insert in column wise [Horizontal Stacking]

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
new_arr = np.insert(arr, 2, 9, axis=0)
print(new_arr)

[1 2 9 3 4 5]


### Insert in 2D Array

In [19]:
import numpy as np

arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,1]]) 
print ("Original Array:\n",arr_2d)
# insert at new row at index 1
new_arr = np.insert(arr_2d,1,[10,11,12,13,14],axis=0)
print ("Array after insertion:\n",new_arr)

Original Array:
 [[1 2 3 4 5]
 [6 7 8 9 1]]
Array after insertion:
 [[ 1  2  3  4  5]
 [10 11 12 13 14]
 [ 6  7  8  9  1]]


In [22]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,1]]) 
print ("Original Array:\n",arr_2d)
# insert at new column at index 1
new_arr = np.insert(arr_2d,1,[10,11],axis=1)
print ("Array after insertion:\n",new_arr)

Original Array:
 [[1 2 3 4 5]
 [6 7 8 9 1]]
Array after insertion:
 [[ 1 10  2  3  4  5]
 [ 6 11  7  8  9  1]]


# Append
- Added array/value at the end

In [24]:
import numpy as np

arr = np.array([1,2,3,4])
print("Original Array:\n", arr)
new_arr = np.append(arr, [5,6,7,8])
print("Array after appending:\n", new_arr)

Original Array:
 [1 2 3 4]
Array after appending:
 [1 2 3 4 5 6 7 8]


# Concatinate

# Syntax
- np.concatinate((array1,array2), axis=0)
- Axis = 0 --> Vertical Stacking
- Axis = 1 --> Horizontal Stacking

In [28]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.concatenate((arr1, arr2))
print("Concatenated Array:\n",new_arr)

Concatenated Array:
 [1 2 3 4 5 6]


# Removing Elements of Array

- np.delete(array,index.no,axis=None)

In [29]:
import numpy as np
arr = np.array([1,2,3,5])
print("Original Array:\n",arr)
new_arr = np.delete(arr, 1)
print("Deleted Array:\n",new_arr)

Original Array:
 [1 2 3 5]
Deleted Array:
 [1 3 5]


In [32]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,1]]) 
print ("Original Array:\n",arr_2d)
new_arr = np.delete(arr_2d,0,axis=0)
print ("Array after Deletion:\n",new_arr)

Original Array:
 [[1 2 3 4 5]
 [6 7 8 9 1]]
Array after Deletion:
 [[6 7 8 9 1]]


In [33]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,1]]) 
print ("Original Array:\n",arr_2d)
new_arr = np.delete(arr_2d,0,axis=1)
print ("Array after Deletion:\n",new_arr)

Original Array:
 [[1 2 3 4 5]
 [6 7 8 9 1]]
Array after Deletion:
 [[2 3 4 5]
 [7 8 9 1]]


# Stacking

### vstack()

In [38]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(f"VerticL stacking:\n {np.vstack((arr1, arr2))}")

VerticL stacking:
 [[1 2 3]
 [4 5 6]]


In [36]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(f"Horizontal stacking: {np.hstack((arr1, arr2))}")

Horizontal stacking: [1 2 3 4 5 6]


# Splitting

### split()

In [56]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(f"Splitting Array: {np.split(arr, 3)}")
# print(np.split(arr, 3))

Splitting Array: [array([10, 20]), array([30, 40]), array([50, 60])]
